name: FodCare
options:
  bundleIdPrefix: com.fodcare
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
targets:
  FodCare:
    type: application
    platform: iOS
    sources:
      - path: FodCare
        excludes:
          - "**/*.xcassets"
    resources:
      - path: FodCare/Resources/Assets.xcassets
      - path: FodCare/Data/SeedData/fodmap_foods_ja.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fodcare.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "フォドケア"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
